micronaut:
  application:
    name: mnFunding
datasources:
  default:
    url: jdbc:mysql://localhost:23306/mn-funding
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mn-funding_user
    password: mn-funding_password
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  datasources:
    default:
      enabled: true
      drop-first: true
      change-log: 'classpath:db/liquibase-changelog.xml'