micronaut:
  application:
    name: mnStockBroker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:secretIsStoredInEnvironmentVariables}"'
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:6432/mn-stock-broker`}
      user: ${PG_USERNAME:art}
      password: ${PG_PASSWORD:secret}
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:6432/mn-stock-broker`}
    driverClassName: org.postgresql.Driver
    username: ${PG_USERNAME:art}
    password: ${PG_PASSWORD:secret}
    schema-generate: NONE
    dialect: POSTGRES
# micronaut-data-jpa
jpa:
  default:
    properties:
      hibernate:
        show_sql: false
        hbm2ddl.auto: none
    packages-to-scan:
      - "net.shyshkin.study.micronaut.broker.persistence"