version: '3'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mn-funding_user
      MYSQL_PASSWORD: mn-funding_password
      MYSQL_DATABASE: mn-funding
    volumes:
      - mn-funding-mysql-data:/var/lib/mysql

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080

volumes:
  mn-funding-mysql-data: